spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
logging:
  level:
    com.portfolio.aicontentstudio: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
